fix planner background and font color when it used with themes
uclixnjupyternbaccessibility/jupyter_contrib_nbextensions pull request #54
Opened 2019-08-15 13:42 UTC by NorahAba

2019-08-16 15:49 UTC, joshuazeltser requested changes
Looks good but when you preview your markdown in the planner the background goes white even when the background colour has been changed?

2019-08-16 16:13 UTC, NorahAba commented
Because I fixed it first then I fixed the themes background color so the themes fix corrupted the first one

2019-08-16 17:11 UTC, NorahAba commented
Done :)

2019-08-20 09:27 UTC, joshuazeltser approved these changes

2019-08-20 09:27 UTC, merged